#!/bin/bash

service openstack-nova-api restart
service openstack-nova-cert restart
service openstack-nova-consoleauth restart
service openstack-nova-scheduler restart
service openstack-nova-conductor restart
service openstack-nova-novncproxy restart
        

#chkconfig openstack-nova-api on
#chkconfig openstack-nova-cert on
#chkconfig openstack-nova-consoleauth on
#chkconfig openstack-nova-scheduler on
#chkconfig openstack-nova-conductor on
#chkconfig openstack-nova-novncproxy on